In [1]:
import pandas as pd
import numpy as np

In [3]:
macd = pd.read_csv('./MACD.csv')

In [4]:
macd

,Unnamed: 0,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum,price
0,0,8.954000,9.238143,8.951500,8.951500,0.000000,0.339056,9.914319,8.561966,8.951500,7.951500,8.951500
1,1,8.954000,9.238143,8.912038,8.910333,-0.001705,0.339056,9.914319,8.561966,8.894500,7.875500,8.875500
2,2,8.954000,9.238143,8.900707,8.898689,-0.002018,0.339056,9.914319,8.561966,8.884808,7.880500,8.880500
3,3,8.954000,9.238143,8.964947,8.971863,0.006916,0.339056,9.914319,8.561966,9.050650,8.130500,9.130500
4,4,8.954000,9.238143,8.956379,8.959946,0.003567,0.339056,9.914319,8.561966,8.968546,7.928000,8.928000
...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2512,169.737071,172.019573,172.005465,170.872064,-1.133401,2.881120,177.781813,166.257334,170.080147,168.669495,169.669495
2513,2513,169.992785,171.802097,171.905875,170.839592,-1.066283,2.489139,176.780374,166.823820,170.467379,169.660995,170.660995
2514,2514,169.876142,171.379359,171.705514,170.587501,-1.118013,2.363310,176.105978,166.652740,169.623129,168.201004,169.201004
2515,2515,170.099786,171.059883,171.478772,170.288578,-1.190194,2.416104,175.892091,166.227674,168.970710,167.644501,168.644501
2516,2516,169.571213,170.799454,171.126048,169.739104,-1.386944,2.587567,175.974588,165.624320,167.468234,165.716995,166.716995

In [5]:
macd = macd.drop(columns={'price','Unnamed: 0'})

In [6]:
macd

,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum
0,8.954000,9.238143,8.951500,8.951500,0.000000,0.339056,9.914319,8.561966,8.951500,7.951500
1,8.954000,9.238143,8.912038,8.910333,-0.001705,0.339056,9.914319,8.561966,8.894500,7.875500
2,8.954000,9.238143,8.900707,8.898689,-0.002018,0.339056,9.914319,8.561966,8.884808,7.880500
3,8.954000,9.238143,8.964947,8.971863,0.006916,0.339056,9.914319,8.561966,9.050650,8.130500
4,8.954000,9.238143,8.956379,8.959946,0.003567,0.339056,9.914319,8.561966,8.968546,7.928000
...,...,...,...,...,...,...,...,...,...,...
2512,169.737071,172.019573,172.005465,170.872064,-1.133401,2.881120,177.781813,166.257334,170.080147,168.669495
2513,169.992785,171.802097,171.905875,170.839592,-1.066283,2.489139,176.780374,166.823820,170.467379,169.660995
2514,169.876142,171.379359,171.705514,170.587501,-1.118013,2.363310,176.105978,166.652740,169.623129,168.201004
2515,170.099786,171.059883,171.478772,170.288578,-1.190194,2.416104,175.892091,166.227674,168.970710,167.644501
2516,169.571213,170.799454,171.126048,169.739104,-1.386944,2.587567,175.974588,165.624320,167.468234,165.716995

In [7]:
old_data = pd.read_csv('./new_dataset.csv')

In [8]:
old_data

,Unnamed: 0,Date,AMZ_Open,AMZ_High,AMZ_Low,AMZ_Close,AMZ_Volume,Dividends,Stock Splits,Apple_Open,...,SP_Volume,VIX_Open,VIX_High,VIX_Low,VIX_Close,polarity,yhat,yhat_upper,yhat_lower,log_diff
0,0,2012-01-03,8.794500,8.974000,8.777500,8.951500,102216000.0,0.0,0.0,12.540048,...,3.943710e+09,22.950001,23.100000,22.540001,22.969999,0.0,6.808257,19.486105,-6.553545,0.000000
1,1,2012-01-04,8.960500,9.025000,8.803500,8.875500,84104000.0,0.0,0.0,12.607435,...,3.592580e+09,23.440001,23.730000,22.219999,22.219999,0.0,6.993756,21.862894,-7.391255,-0.008526
2,2,2012-01-05,8.797000,8.912500,8.702500,8.880500,76182000.0,0.0,0.0,12.747405,...,4.315950e+09,22.750000,23.090000,21.340000,21.480000,0.0,7.106478,20.389897,-6.713558,0.000563
3,3,2012-01-06,8.903500,9.232500,8.875000,9.130500,140168000.0,0.0,0.0,12.880662,...,3.656830e+09,21.240000,21.719999,20.580000,20.629999,0.0,7.017323,21.386000,-6.638345,0.027763
4,4,2012-01-09,9.138000,9.218500,8.850000,8.928000,101138000.0,0.0,0.0,12.860233,...,3.371600e+09,21.670000,21.780001,21.000000,21.070000,0.0,7.464025,22.195410,-7.301672,-0.022428
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2512,2021-12-27,171.037003,172.942993,169.215500,169.669495,58688000.0,0.0,0.0,179.586868,...,2.264120e+09,19.370001,19.410000,17.549999,17.680000,0.0,187.237354,200.869817,172.641770,-0.008212
2513,2513,2021-12-28,170.182495,172.175995,169.135498,170.660995,54638000.0,0.0,0.0,178.551132,...,2.217050e+09,17.780001,18.469999,17.510000,17.540001,0.0,187.634934,201.744047,173.763224,0.005827
2514,2514,2021-12-29,170.839996,171.212006,168.600494,169.201004,35754000.0,0.0,0.0,178.640778,...,2.369370e+09,17.629999,18.000000,16.709999,16.950001,0.0,187.899439,200.904501,173.503755,-0.008592
2515,2515,2021-12-30,169.699997,170.888000,168.524002,168.644501,37584000.0,0.0,0.0,177.465637,...,2.390990e+09,17.299999,17.790001,16.620001,17.330000,0.0,188.099826,202.519201,175.793765,-0.003294
2516,2516,2021-12-31,168.955994,169.350006,166.558502,166.716995,47830000.0,0.0,0.0,176.838257,...,2.446190e+09,17.629999,18.270000,16.990000,17.219999,0.0,188.106782,203.813356,174.543234,-0.011495

In [14]:
new_data = old_data.join(macd)

In [15]:
new_data

,Unnamed: 0,Date,AMZ_Open,AMZ_High,AMZ_Low,AMZ_Close,AMZ_Volume,Dividends,Stock Splits,Apple_Open,...,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum
0,0,2012-01-03,8.794500,8.974000,8.777500,8.951500,102216000.0,0.0,0.0,12.540048,...,8.954000,9.238143,8.951500,8.951500,0.000000,0.339056,9.914319,8.561966,8.951500,7.951500
1,1,2012-01-04,8.960500,9.025000,8.803500,8.875500,84104000.0,0.0,0.0,12.607435,...,8.954000,9.238143,8.912038,8.910333,-0.001705,0.339056,9.914319,8.561966,8.894500,7.875500
2,2,2012-01-05,8.797000,8.912500,8.702500,8.880500,76182000.0,0.0,0.0,12.747405,...,8.954000,9.238143,8.900707,8.898689,-0.002018,0.339056,9.914319,8.561966,8.884808,7.880500
3,3,2012-01-06,8.903500,9.232500,8.875000,9.130500,140168000.0,0.0,0.0,12.880662,...,8.954000,9.238143,8.964947,8.971863,0.006916,0.339056,9.914319,8.561966,9.050650,8.130500
4,4,2012-01-09,9.138000,9.218500,8.850000,8.928000,101138000.0,0.0,0.0,12.860233,...,8.954000,9.238143,8.956379,8.959946,0.003567,0.339056,9.914319,8.561966,8.968546,7.928000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,2512,2021-12-27,171.037003,172.942993,169.215500,169.669495,58688000.0,0.0,0.0,179.586868,...,169.737071,172.019573,172.005465,170.872064,-1.133401,2.881120,177.781813,166.257334,170.080147,168.669495
2513,2513,2021-12-28,170.182495,172.175995,169.135498,170.660995,54638000.0,0.0,0.0,178.551132,...,169.992785,171.802097,171.905875,170.839592,-1.066283,2.489139,176.780374,166.823820,170.467379,169.660995
2514,2514,2021-12-29,170.839996,171.212006,168.600494,169.201004,35754000.0,0.0,0.0,178.640778,...,169.876142,171.379359,171.705514,170.587501,-1.118013,2.363310,176.105978,166.652740,169.623129,168.201004
2515,2515,2021-12-30,169.699997,170.888000,168.524002,168.644501,37584000.0,0.0,0.0,177.465637,...,170.099786,171.059883,171.478772,170.288578,-1.190194,2.416104,175.892091,166.227674,168.970710,167.644501
2516,2516,2021-12-31,168.955994,169.350006,166.558502,166.716995,47830000.0,0.0,0.0,176.838257,...,169.571213,170.799454,171.126048,169.739104,-1.386944,2.587567,175.974588,165.624320,167.468234,165.716995

In [16]:
new_data = new_data.set_index('Date')

In [19]:
new_data

,Unnamed: 0,AMZ_Open,AMZ_High,AMZ_Low,AMZ_Close,AMZ_Volume,Dividends,Stock Splits,Apple_Open,Apple_High,...,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum
Date,,,,,,,,,,,,,,,,,,,,,
2012-01-03,0,8.794500,8.974000,8.777500,8.951500,102216000.0,0.0,0.0,12.540048,12.578776,...,8.954000,9.238143,8.951500,8.951500,0.000000,0.339056,9.914319,8.561966,8.951500,7.951500
2012-01-04,1,8.960500,9.025000,8.803500,8.875500,84104000.0,0.0,0.0,12.607435,12.645249,...,8.954000,9.238143,8.912038,8.910333,-0.001705,0.339056,9.914319,8.561966,8.894500,7.875500
2012-01-05,2,8.797000,8.912500,8.702500,8.880500,76182000.0,0.0,0.0,12.747405,12.763261,...,8.954000,9.238143,8.900707,8.898689,-0.002018,0.339056,9.914319,8.561966,8.884808,7.880500
2012-01-06,3,8.903500,9.232500,8.875000,9.130500,140168000.0,0.0,0.0,12.880662,12.891335,...,8.954000,9.238143,8.964947,8.971863,0.006916,0.339056,9.914319,8.561966,9.050650,8.130500
2012-01-09,4,9.138000,9.218500,8.850000,8.928000,101138000.0,0.0,0.0,12.860233,13.043807,...,8.954000,9.238143,8.956379,8.959946,0.003567,0.339056,9.914319,8.561966,8.968546,7.928000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,2512,171.037003,172.942993,169.215500,169.669495,58688000.0,0.0,0.0,179.586868,179.676494,...,169.737071,172.019573,172.005465,170.872064,-1.133401,2.881120,177.781813,166.257334,170.080147,168.669495
2021-12-28,2513,170.182495,172.175995,169.135498,170.660995,54638000.0,0.0,0.0,178.551132,180.582734,...,169.992785,171.802097,171.905875,170.839592,-1.066283,2.489139,176.780374,166.823820,170.467379,169.660995
2021-12-29,2514,170.839996,171.212006,168.600494,169.201004,35754000.0,0.0,0.0,178.640778,179.885626,...,169.876142,171.379359,171.705514,170.587501,-1.118013,2.363310,176.105978,166.652740,169.623129,168.201004
2021-12-30,2515,169.699997,170.888000,168.524002,168.644501,37584000.0,0.0,0.0,177.465637,179.825881,...,170.099786,171.059883,171.478772,170.288578,-1.190194,2.416104,175.892091,166.227674,168.970710,167.644501
2021-12-31,2516,168.955994,169.350006,166.558502,166.716995,47830000.0,0.0,0.0,176.838257,178.491405,...,169.571213,170.799454,171.126048,169.739104,-1.386944,2.587567,175.974588,165.624320,167.468234,165.716995

In [18]:
new_data.tail(10)

,Unnamed: 0,AMZ_Open,AMZ_High,AMZ_Low,AMZ_Close,AMZ_Volume,Dividends,Stock Splits,Apple_Open,Apple_High,...,ma7,ma21,26ema,12ema,MACD,20sd,upper_band,lower_band,ema,momentum
Date,,,,,,,,,,,,,,,,,,,,,
2021-12-17,2507,167.710495,170.898499,165.613495,170.017502,85542000.0,0.0,0.0,170.434723,172.755123,...,171.035076,174.686787,172.975864,171.985186,-0.990679,4.114269,182.915326,166.458249,169.992784,169.017502
2021-12-20,2508,166.850006,167.874496,165.600006,167.078995,57372000.0,0.0,0.0,169.050461,169.877042,...,170.021931,173.842787,172.539059,171.230387,-1.308672,3.734287,181.311361,166.374214,168.050258,166.078995
2021-12-21,2509,167.850494,170.716507,165.647507,170.417007,55956000.0,0.0,0.0,172.277100,172.486226,...,169.765503,173.204144,172.381870,171.105252,-1.276618,3.570455,180.345054,166.063234,169.628091,169.417007
2021-12-22,2510,169.270004,172.050003,168.500504,171.037003,55036000.0,0.0,0.0,174.916183,175.135278,...,169.975431,172.842645,172.282250,171.094752,-1.187498,3.291166,179.424976,166.260313,170.567365,170.037003
2021-12-23,2511,170.427994,171.975006,170.149994,171.068497,36788000.0,0.0,0.0,175.553543,176.121201,...,170.257858,172.464859,172.192343,171.090713,-1.101630,2.926520,178.317899,166.611820,170.901453,170.068497
2021-12-27,2512,171.037003,172.942993,169.215500,169.669495,58688000.0,0.0,0.0,179.586868,179.676494,...,169.737071,172.019573,172.005465,170.872064,-1.133401,2.881120,177.781813,166.257334,170.080147,168.669495
2021-12-28,2513,170.182495,172.175995,169.135498,170.660995,54638000.0,0.0,0.0,178.551132,180.582734,...,169.992785,171.802097,171.905875,170.839592,-1.066283,2.489139,176.780374,166.823820,170.467379,169.660995
2021-12-29,2514,170.839996,171.212006,168.600494,169.201004,35754000.0,0.0,0.0,178.640778,179.885626,...,169.876142,171.379359,171.705514,170.587501,-1.118013,2.363310,176.105978,166.652740,169.623129,168.201004
2021-12-30,2515,169.699997,170.888000,168.524002,168.644501,37584000.0,0.0,0.0,177.465637,179.825881,...,170.099786,171.059883,171.478772,170.288578,-1.190194,2.416104,175.892091,166.227674,168.970710,167.644501
2021-12-31,2516,168.955994,169.350006,166.558502,166.716995,47830000.0,0.0,0.0,176.838257,178.491405,...,169.571213,170.799454,171.126048,169.739104,-1.386944,2.587567,175.974588,165.624320,167.468234,165.716995

In [21]:
new_data.to_csv('./complete_data.csv')